import { Order } from "./orders.types";



export const orders: Order[] = [
  {
    id: 1,
    date: "11/20/2025",
    patientName: "John Doe",
    orderType: "Medication Orders",
    serviceType: "Hospice",
    agency: "ABC Pvt-Ltd",
    labels: [{ text: "LD", color: "bg-red-500" }],
    receivedVia: "Symmetry",
    orderReceived: "Today | 07:30 AM",
    tags: ["Modified"],
    day: "Today",
  },
  {
    id: 2,
    date: "11/01/2025",
    patientName: "Oliver Bennett",
    orderType: "MD Verification",
    serviceType: "Home Health",
    agency: "ABC Pvt-Ltd",
    labels: [
      { text: "UR", color: "bg-blue-500" },
      { text: "PS", color: "bg-green-500" },
      { text: "CR", color: "bg-amber-700" },
    ],
    receivedVia: "Email",
    orderReceived: "Today | 07:30 AM",
    tags: [],
    day: "2 Days",
  },
  {
    id: 3,
    date: "10/15/2025",
    patientName: "Amelia Carter",
    orderType: "Skilled Nursing Orders",
    serviceType: "Home Health",
    agency: "ABC Pvt-Ltd",
    labels: [{ text: "DME", color: "bg-orange-500" }],
    receivedVia: "efax",
    orderReceived: "Today | 09:00 AM",
    tags: ["Outbound"],
    day: "7 Days",
  },
  {
    id: 4,
    date: "09/27/2025",
    patientName: "Taylor Sutton",
    orderType: "Equipment and Supplies Orders",
    serviceType: "Hospice",
    agency: "ABC Pvt-Ltd",
    labels: [{ text: "CR", color: "bg-amber-700" }],
    receivedVia: "Email",
    orderReceived: "Today | 09:00 AM",
    tags: [],
    day: "2 Days",
  },
  {
    id: 5,
    date: "06/21/2025",
    patientName: "Sophie Harrington",
    orderType: "Lab, Diagnostic, or Procedure Orders",
    serviceType: "Hospice",
    agency: "ABC Pvt-Ltd",
    labels: [
      { text: "LD", color: "bg-red-500" },
      { text: "UR", color: "bg-blue-500" },
    ],
    receivedVia: "Symmetry",
    orderReceived: "Today | 09:00 AM",
    tags: ["Modified"],
    day: "5 Days",
  },
  {
    id: 6,
    date: "05/18/2025",
    patientName: "Charles Turner",
    orderType: "Plan of Care / Certification Orders",
    serviceType: "Home Health",
    agency: "ABC Pvt-Ltd",
    labels: [{ text: "PS", color: "bg-green-500" }],
    receivedVia: "Email",
    orderReceived: "Today | 09:00 AM",
    tags: ["Modified", "Outbound"],
    day: "Today",
  },
];

export const tabs = [
  { label: "Today", count: 22 },
  { label: "Unopened", count: 41 },
  { label: "Unsigned", count: 20 },
  { label: "Undelivered", count: null },
  { label: "Rejected", count: 1, alert: true },
  { label: "Completed", count: null },
];